### PR TITLE
Makes build state `public`changeable in the UI

### PR DESCRIPTION
**Pull request by elsigh**
Allows setting the "public" property for a build.

### CODE REVIEW

**Comment by bslatkin** [comment]
Looks like the flask mail build is busted. Doh.

**Comment by elsigh** [comment]
I believe that's due to https://github.com/bslatkin/dpxdt/issues/138

**Comment by bslatkin** [comment]
Okay I fixed #138 can you rebase?

**Comment by elsigh** [comment]
ok, rebased and repushed - looks like Travis is happy =)

**Pull request merged**
